-- MySQL Script generated by MySQL Workbench
-- 05/30/14 11:15:40
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prz` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `prz` ;

-- -----------------------------------------------------
-- Table `prz`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`sale` ;

CREATE TABLE IF NOT EXISTS `prz`.`sale` (
  `nr` INT(11) NOT NULL,
  `miejsca` INT(11) NOT NULL,
  PRIMARY KEY (`nr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prz`.`wymagania_przedmiotowe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`wymagania_przedmiotowe` ;

CREATE TABLE IF NOT EXISTS `prz`.`wymagania_przedmiotowe` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prz`.`sale_wym`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`sale_wym` ;

CREATE TABLE IF NOT EXISTS `prz`.`sale_wym` (
  `id_sala` INT(11) NOT NULL,
  `id_wym` INT(11) NOT NULL,
  INDEX `id_wym` (`id_wym` ASC),
  INDEX `id_sala` (`id_sala` ASC),
  CONSTRAINT `id_sala`
    FOREIGN KEY (`id_sala`)
    REFERENCES `prz`.`sale` (`nr`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_wym`
    FOREIGN KEY (`id_wym`)
    REFERENCES `prz`.`wymagania_przedmiotowe` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prz`.`wykladowcy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`wykladowcy` ;

CREATE TABLE IF NOT EXISTS `prz`.`wykladowcy` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(20) NOT NULL,
  `nazwisko` VARCHAR(30) NOT NULL,
  `tytul` VARCHAR(10) NOT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  `min_etat` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `full_name` (`imie` ASC, `nazwisko` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prz`.`kierunki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`kierunki` ;

CREATE TABLE IF NOT EXISTS `prz`.`kierunki` (
  `nazwa` VARCHAR(20) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `nazwa_UNIQUE` (`nazwa` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prz`.`przedmiot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`przedmiot` ;

CREATE TABLE IF NOT EXISTS `prz`.`przedmiot` (
  `nazwa` VARCHAR(45) NOT NULL,
  `skrot` VARCHAR(5) NOT NULL,
  `kierunek` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `tryb` TINYINT(1) NOT NULL,
  UNIQUE INDEX `UNIQUE` (`nazwa` ASC, `skrot` ASC, `kierunek` ASC),
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`kierunek` ASC),
  CONSTRAINT `k_id`
    FOREIGN KEY (`kierunek`)
    REFERENCES `prz`.`kierunki` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prz`.`przedmiot_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`przedmiot_type` ;

CREATE TABLE IF NOT EXISTS `prz`.`przedmiot_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nazwa_UNIQUE` (`nazwa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prz`.`przedmiot_part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`przedmiot_part` ;

CREATE TABLE IF NOT EXISTS `prz`.`przedmiot_part` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_przedmiot` INT NOT NULL,
  `id_wykladowca` INT NULL,
  `godziny` INT NOT NULL,
  `id_wym` INT NULL,
  `id_type` INT NOT NULL,
  `id_grupy` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_przedmiot_idx` (`id_przedmiot` ASC),
  INDEX `id_wylkadowca_idx` (`id_wykladowca` ASC),
  INDEX `id_wym_idx` (`id_wym` ASC),
  INDEX `id_type_idx` (`id_type` ASC),
  CONSTRAINT `id_przedmiot`
    FOREIGN KEY (`id_przedmiot`)
    REFERENCES `prz`.`przedmiot` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_wykladowca`
    FOREIGN KEY (`id_wykladowca`)
    REFERENCES `prz`.`wykladowcy` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `id_wym_pp`
    FOREIGN KEY (`id_wym`)
    REFERENCES `prz`.`wymagania_przedmiotowe` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `id_type`
    FOREIGN KEY (`id_type`)
    REFERENCES `prz`.`przedmiot_type` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prz`.`godziny_p`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`godziny_p` ;

CREATE TABLE IF NOT EXISTS `prz`.`godziny_p` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` TIME NOT NULL,
  `end` TIME NOT NULL,
  `day` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prz`.`pp_godz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`pp_godz` ;

CREATE TABLE IF NOT EXISTS `prz`.`pp_godz` (
  `id_pp` INT NOT NULL,
  `id_godz` INT NOT NULL,
  INDEX `id_pp_idx` (`id_pp` ASC),
  INDEX `id_godz_idx` (`id_godz` ASC),
  CONSTRAINT `id_pp`
    FOREIGN KEY (`id_pp`)
    REFERENCES `prz`.`przedmiot_part` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_godz`
    FOREIGN KEY (`id_godz`)
    REFERENCES `prz`.`godziny_p` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prz`.`godziny_w`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`godziny_w` ;

CREATE TABLE IF NOT EXISTS `prz`.`godziny_w` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` TIME NOT NULL,
  `end` TIME NOT NULL,
  `day` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prz`.`w_godz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prz`.`w_godz` ;

CREATE TABLE IF NOT EXISTS `prz`.`w_godz` (
  `id_w` INT NOT NULL,
  `id_godz` INT NOT NULL,
  INDEX `id_idx` (`id_godz` ASC),
  INDEX `id_idx1` (`id_w` ASC),
  CONSTRAINT `id_g`
    FOREIGN KEY (`id_godz`)
    REFERENCES `prz`.`godziny_w` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_w`
    FOREIGN KEY (`id_w`)
    REFERENCES `prz`.`wykladowcy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;